apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: image-updater
  namespace: argocd
spec:
  commonUpdateSettings:
    pullsecret: argocd/harbor-dockerconfigjson
  applicationRefs:
    - namePattern: "k8s-demo-dev"
      images:
        - alias: "k8s-demo-dev"
          imageName: "harbor.sabihinmolang.eu.org/demo/demo-dev:latest"
          commonUpdateSettings:
            updateStrategy: "digest"
    - namePattern: "k8s-ironcurtain-be-helm"
      images:
        - alias: "k8s-ironcurtain-be-helm"
          imageName: "quay.io/veenoise/k8s-ironcurtain-be:latest"
          commonUpdateSettings:
            updateStrategy: "digest"
    - namePattern: "k8s-ironcurtain-fe-helm"
      images:
        - alias: "k8s-ironcurtain-fe-helm"
          imageName: "quay.io/veenoise/k8s-ironcurtain-fe:latest"
          commonUpdateSettings:
            updateStrategy: "digest"
    - namePattern: "dev-k8s-next-demo-helm"
      images:
        - alias: "dev-k8s-next-demo-helm"
          imageName: "quay.io/veenoise/k8s-next-demo:develop"
          commonUpdateSettings:
            updateStrategy: "digest"
    - namePattern: "staging-k8s-next-demo-helm"
      images:
        - alias: "staging-k8s-next-demo-helm"
          imageName: "quay.io/veenoise/k8s-next-demo:staging"
          commonUpdateSettings:
            updateStrategy: "digest"
    - namePattern: "main-k8s-next-demo-helm"
      images:
        - alias: "main-k8s-next-demo-helm"
          imageName: "quay.io/veenoise/k8s-next-demo:main"
          commonUpdateSettings:
            updateStrategy: "digest"
