apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: image-updater
  namespace: argocd
spec:
  commonUpdateSettings:
    pullsecret: argocd/harbor-dockerconfigjson
  applicationRefs:
    - namePattern: "k8s-demo-dev"
      images:
        - alias: "k8s-demo-dev"
          imageName: "harbor.sabihinmolang.eu.org/demo/demo-dev:latest"
          commonUpdateSettings:
            updateStrategy: "digest"
    - namePattern: "k8s-ironcurtain-be"
      images:
        - alias: "k8s-ironcurtain-be"
          imageName: "quay.io/veenoise/k8s-ironcurtain-be:latest"
          commonUpdateSettings:
            updateStrategy: "digest"
    - namePattern: "k8s-ironcurtain-fe"
      images:
        - alias: "k8s-ironcurtain-fe"
          imageName: "quay.io/veenoise/k8s-ironcurtain-fe:latest"
          commonUpdateSettings:
            updateStrategy: "digest"